### ISSUE TITLE
Throws Unauthorized Exception

### ISSUE THREAD

**Issue by rajkumarkscme** [MOSDEV82/fcmhelper#3]
Exception in thread "main" org.apache.http.client.HttpResponseException: Unauthorized
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:69)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:65)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:51)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ppts.dd.util.FCMHelper.sendFcmMessage(FCMHelper.java:183)
	at com.ppts.dd.util.FCMHelper.sendNotifictaionAndData(FCMHelper.java:99)
	at com.ppts.dd.util.FCMHelper.sendData(FCMHelper.java:79)
	at com.ppts.dd.util.FCMHelper.sendTopicData(FCMHelper.java:114)
	at com.ppts.dd.util.FCMHelper.main(FCMHelper.java:196)

**My main method jsonobject**
JsonObject obj = new JsonObject();
obj.addProperty("title", "Background Message Title");
obj.addProperty("body", "Background message body");

can u help me out this how to resolve.
also provide main method call functions and input.

thanks

**Comment by MOSDEV82** [comment]
Unauthorized Exception means that your "Server key" is not correct. Please use the key from your firebase console.
